app1/urls.py
from unicodedata import name
from django import views
from django.urls import path
from . import views

app_name = 'app1'

urlpatterns = [
    path('',views.index,name='index'),
    path('teacher',views.teacher,name='teach'),
    path('viewteachers',views.view_teacher,name='viewteacher'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app1.urls')),
]

app1/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    name = models.CharField(max_length=20)
    age = models.IntegerField()
    mark = models.FloatField()


class Teacher(models.Model):
    name = models.CharField(max_length=20)
    age = models.IntegerField()
    

app1/views.py
from unicodedata import name
from django.shortcuts import render
from . models import Student,Teacher

# Create your views here.
def index(request):
    if request.method=='POST':
        std_name = request.POST["uname"]
        std_age = request.POST["uage"]
        std_mark = request.POST["umark"]
        std1 = Student(name=std_name,age=std_age,mark=std_mark)
        std1.save()


    return render(request,'index.html')

def teacher(request):
    if request.method == 'POST':
        t_name = request.POST["tname"]
        t_age = request.POST["tage"]
        teacher1 = Teacher(name=t_name,age=t_age)
        teacher1.save()
        msg = "teacher added successfully"
        return render(request,'teacher.html',{'msg':msg,})
    

    return render(request,'teacher.html')

def view_teacher(request):
    teachers = Teacher.objects.all()
    return render(request,'viewteachers.html',{'details':teachers,})

app1/templates/app1/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</head>
<body>
    <h1>ahsdbalhs</h1>
    <h1>welcome {{user|capfirst}}</h1>
    <h1>welcome {{user|title}}</h1>
    <p>
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Temporibus libero sapiente quibusdam fugit inventore
         nesciunt voluptatem consectetur voluptate tempore recusandae.

    </p>

<!-- 
{% if 'customerid' in request.session %}
<div class="btn-group">
    <a class="dropdown-items" href="/ecom/logout" type="button">logout<i class="fa-fa-sign-out" aria-hidden="true"></i></a>
</div>
{% else %}
<div class="login-nav">
    <button onclick="location.href = 'login'" type="button" class="btn">login</button>
</div>
{% endif %}

<table>

    {% for data in resellerdata %}
        <tr>
            <td style="border: 1px gray solid;">{{data.companyregid}}</td>
            <td style="border: 1px gray solid;">{{data.companyname}}</td>
            <td style="border: 1px gray solid;">{{data.country}}</td>
            <td style="border: 1px gray solid;">{{data.status}}</td>
        </tr>

    {% endfor %} -->

    {% if type == 'dev' %}

    <div>Development</div>
    {% else %}
    <div>Testing</div>

    {% endif %}
        <p></p>

        <form method="POST" action="{% url 'app1:index' %}"> 
            {% csrf_token %}
            <label>name</label>
            <input type="text" name="uname"><br>
            <label>age</label>
            <input type="number" name="uage"><br>
            <label>mark</label>
            <input type="number" name="umark"><br>
            <button type="submit">Submit</button>
        </form>
        

       
</table>
</body>
</html>

app1/templates/app1/teacher.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="POST" action=""> 
        {% csrf_token %}
        <label>Teacher name</label>
        <input type="text" name="tname"><br>
        <label>Teacher age</label>
        <input type="number" name="tage"><br>
        
        <button type="submit">Submit</button>
        {{msg}}
    </form>
    <a href="{% url 'app1:viewteacher'%}">view teachers</a>
</body>
</html>

app1/templates/app1/viewteachers.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <table>
        <tr>
            <th>Name:</th>
            <th>Age:</th>
        </tr>
        {% for t in details %}
        <tr>
            <td>{{t.id}}</td>
            <td>{{t.name}}</td>
            <td>{{t.age}}</td>
            
        </tr>
        {% endfor %}
    </table>
</body>
</html>